const Products = [
  
    {
      id: 2,
      title: "Pink-Perfume",
      image: ["/perfume11.png", "/perfume11.png"],
      slug: "lader",
      price: 9000,
      category: "accessories",
      description: "A beautiful bottle",
      size: ["S", "M", "L"],
      color: ["red", "blue", "black"],
      qty: 1,
      discount: 20,
    },
    {
      id: 3,
      title: "Golden Perfume-Bottle",
      image: ["/perfume15.png", "/perfume15.png"],
      slug: "running-shoes",
      price: 7000,
      category: "footwear",
      description: "A beautiful bottle",
      size: ["S", "M", "L"],
      color: ["red", "blue", "black"],
      qty: 1,
      discount: 10,
    },
    {
      id: 4,
      title: "T-pink Perfume-Bottle",
      image: ["/perfume3.png", "/perfume3.png"],
      slug: "smart-watch",
      price: 6000,
      category: "electronics",
      description: "A beautiful bottle",
      size: ["S", "M", "L"],
      color: ["red", "blue", "black"],
      qty: 1,
      discount: 10,
    },
    {
      id: 5,
      title: "Oringe Perfume-Bottle",
      image: ["/perfume6.png", "/perfume6.png"],
      slug: "perfume",
      price: 10000,
      category: "electronics",
      description: "A beautiful bottle",
      size: ["S", "M", "L"],
      color: ["red", "blue", "black"],
      qty: 1,
      discount: 10,
    },
    {
      id: 6,
      title: "crystal Perfume-Bottle",
      image: ["/perfume12.png", "/perfume12.png"],
      slug: "smart-watchh",
      price: 12000,
      category: "electronics",
      description: "A beautiful bottle",
      size: ["S", "M", "L"],
      color: ["red", "blue", "black"],
      qty: 1,
      discount: 10,
    },
    {
      id: 7,
      title: "Liquid Perfume-Bottle",
      image: ["/perfume5.png", "/perfume5.png"],
      slug: "smart-watchs",
      price: 12000,
      category: "electronics",
      description: "A beautiful bottle",
      size: ["S", "M", "L"],
      color: ["red", "blue", "black"],
      qty: 1,
      discount: 10,
    },
    {
      id: 8,
      title: "stylish Perfume-Bottle",
      image: ["/perfume9.png", "/perfume9.png"],
      slug: "smart-watch",
      price: 15000,
      category: "electronics",
      description: "A beautiful bottle",
      size: ["S", "M", "L"],
      color: ["red", "blue", "black"],
      qty: 1,
      discount: 10,
    },
    {
      id: 9,
      title: "multiple Perfume-Bottle",
      image: ["/perfume7.png", "/perfume7.png"],
      slug: "smart-watch",
      price: 55000,
      category: "electronics",
      description: "A beautiful bottle",
      size: ["S", "M", "L"],
      color: ["red", "blue", "black"],
      qty: 1,
      discount: 10,
    },
    // {
    //   id: 10,
    //   title: "Stylish Perfume-Bottle",
    //   image: ["/perfume9.png", "/perfume9.png"],
    //   slug: "smart-watch",
    //   price: 15000,
    //   category: "electronics",
    //   description: "A beautiful bottle",
    //   size: ["S", "M", "L"],
    //   color: ["red", "blue", "black"],
    //   qty: 1,
    //   discount: 10,
    // },
    
    
  ];
  export default Products